# Generated by Django 3.1.5 on 2021-03-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=10)),
                ('meetcode', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='chatdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('relatehost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.host')),
            ],
        ),
    ]
